/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/changelog': RouteRecordInfo<'/changelog', '/changelog', Record<never, never>, Record<never, never>>,
    '/changelog/': RouteRecordInfo<'/changelog/', '/changelog', Record<never, never>, Record<never, never>>,
    '/changelog/0.1.15': RouteRecordInfo<'/changelog/0.1.15', '/changelog/0/1/15', Record<never, never>, Record<never, never>>,
    '/changelog/0.1.16': RouteRecordInfo<'/changelog/0.1.16', '/changelog/0/1/16', Record<never, never>, Record<never, never>>,
    '/changelog/0.1.18': RouteRecordInfo<'/changelog/0.1.18', '/changelog/0/1/18', Record<never, never>, Record<never, never>>,
    '/changelog/0.1.20': RouteRecordInfo<'/changelog/0.1.20', '/changelog/0/1/20', Record<never, never>, Record<never, never>>,
    '/changelog/0.1.21': RouteRecordInfo<'/changelog/0.1.21', '/changelog/0/1/21', Record<never, never>, Record<never, never>>,
    '/changelog/0.1.23': RouteRecordInfo<'/changelog/0.1.23', '/changelog/0/1/23', Record<never, never>, Record<never, never>>,
    '/changelog/0.1.25': RouteRecordInfo<'/changelog/0.1.25', '/changelog/0/1/25', Record<never, never>, Record<never, never>>,
    '/changelog/0.1.26': RouteRecordInfo<'/changelog/0.1.26', '/changelog/0/1/26', Record<never, never>, Record<never, never>>,
    '/changelog/0.1.27': RouteRecordInfo<'/changelog/0.1.27', '/changelog/0/1/27', Record<never, never>, Record<never, never>>,
    '/changelog/0.1.28': RouteRecordInfo<'/changelog/0.1.28', '/changelog/0/1/28', Record<never, never>, Record<never, never>>,
    '/changelog/0.1.29': RouteRecordInfo<'/changelog/0.1.29', '/changelog/0/1/29', Record<never, never>, Record<never, never>>,
    '/data': RouteRecordInfo<'/data', '/data', Record<never, never>, Record<never, never>>,
    '/data/': RouteRecordInfo<'/data/', '/data', Record<never, never>, Record<never, never>>,
    '/data/ability': RouteRecordInfo<'/data/ability', '/data/ability', Record<never, never>, Record<never, never>>,
    '/data/bestiary': RouteRecordInfo<'/data/bestiary', '/data/bestiary', Record<never, never>, Record<never, never>>,
    '/data/challenge': RouteRecordInfo<'/data/challenge', '/data/challenge', Record<never, never>, Record<never, never>>,
    '/data/challenge/': RouteRecordInfo<'/data/challenge/', '/data/challenge', Record<never, never>, Record<never, never>>,
    '/data/challenge/handicap': RouteRecordInfo<'/data/challenge/handicap', '/data/challenge/handicap', Record<never, never>, Record<never, never>>,
    '/data/challenge/solo': RouteRecordInfo<'/data/challenge/solo', '/data/challenge/solo', Record<never, never>, Record<never, never>>,
    '/data/challenge/superdungeon': RouteRecordInfo<'/data/challenge/superdungeon', '/data/challenge/superdungeon', Record<never, never>, Record<never, never>>,
    '/data/expedition': RouteRecordInfo<'/data/expedition', '/data/expedition', Record<never, never>, Record<never, never>>,
    '/data/guild': RouteRecordInfo<'/data/guild', '/data/guild', Record<never, never>, Record<never, never>>,
    '/data/quest': RouteRecordInfo<'/data/quest', '/data/quest', Record<never, never>, Record<never, never>>,
    '/data/quest/': RouteRecordInfo<'/data/quest/', '/data/quest', Record<never, never>, Record<never, never>>,
    '/data/quest/global': RouteRecordInfo<'/data/quest/global', '/data/quest/global', Record<never, never>, Record<never, never>>,
    '/data/quest/title': RouteRecordInfo<'/data/quest/title', '/data/quest/title', Record<never, never>, Record<never, never>>,
    '/data/super-dungeon': RouteRecordInfo<'/data/super-dungeon', '/data/super-dungeon', Record<never, never>, Record<never, never>>,
    '/data/super-dungeon/': RouteRecordInfo<'/data/super-dungeon/', '/data/super-dungeon', Record<never, never>, Record<never, never>>,
    '/data/super-dungeon/powerup': RouteRecordInfo<'/data/super-dungeon/powerup', '/data/super-dungeon/powerup', Record<never, never>, Record<never, never>>,
    '/data/super-dungeon/ritual': RouteRecordInfo<'/data/super-dungeon/ritual', '/data/super-dungeon/ritual', Record<never, never>, Record<never, never>>,
    '/data/super-dungeon/ruby-shop': RouteRecordInfo<'/data/super-dungeon/ruby-shop', '/data/super-dungeon/ruby-shop', Record<never, never>, Record<never, never>>,
    '/data/super-dungeon/upgrade': RouteRecordInfo<'/data/super-dungeon/upgrade', '/data/super-dungeon/upgrade', Record<never, never>, Record<never, never>>,
    '/data/talisman': RouteRecordInfo<'/data/talisman', '/data/talisman', Record<never, never>, Record<never, never>>,
    '/data/town': RouteRecordInfo<'/data/town', '/data/town', Record<never, never>, Record<never, never>>,
    '/drop-chance': RouteRecordInfo<'/drop-chance', '/drop-chance', Record<never, never>, Record<never, never>>,
    '/equipment': RouteRecordInfo<'/equipment', '/equipment', Record<never, never>, Record<never, never>>,
    '/expedition': RouteRecordInfo<'/expedition', '/expedition', Record<never, never>, Record<never, never>>,
    '/guild': RouteRecordInfo<'/guild', '/guild', Record<never, never>, Record<never, never>>,
    '/help': RouteRecordInfo<'/help', '/help', Record<never, never>, Record<never, never>>,
    '/ruby-shard': RouteRecordInfo<'/ruby-shard', '/ruby-shard', Record<never, never>, Record<never, never>>,
    '/talisman': RouteRecordInfo<'/talisman', '/talisman', Record<never, never>, Record<never, never>>,
    '/test': RouteRecordInfo<'/test', '/test', Record<never, never>, Record<never, never>>,
  }
}
