export enum AchievementRewardKind {
  EpicCoin,
  PortalOrb,
  Nitro,
  GoldCap,
  ResourceGain,
  ExpGain,
  EQInventorySlot,
  UtilityInventorySlot,
  TamingPoint,
  EquipmentDrop,
  EquipmentProficiency,
  ArtifactProficiency,
  SkillProficiency,
  SPD,
  Essence,
}
