export enum GuildSuperAbilityKind {
  SuperMining,
  SuperSynthesizing,
  SuperGathering,
  SuperTraining,
  SuperTrapping,
  SuperBanking,
  SuperFinancing,
  Finding,
  Racing,
  Socializing,
  Ritualizing,
  Artificing,
  Haggling,
}
