export const potionKind = [
  "Nothing",
  "MinorHealthPotion",
  "MinorRegenerationPoultice",
  "MinorResourcePoultice",
  "SlickShoeSolution",
  "MinorManaRegenerationPoultice",
  "MaterialMultiplierMist",
  "BasicElixirOfBrawn",
  "BasicElixirOfBrains",
  "BasicElixirOfFortitude",
  "BasicElixirOfConcentration",
  "BasicElixirOfUnderstanding",
  "ChilledHealthPotion",
  "ChilledRegenerationPoultice",
  "FrostyDefensePotion",
  "IcyAuraDraught",
  "SlightlyStickySalve",
  "SlickerShoeSolution",
  "CoolHeadOintment",
  "FrostySlayersOil",
  "BurningDefensePotion",
  "BlazingAuraDraught",
  "FierySlayersOil",
  "ElectricDefensePotion",
  "WhirlingAuraDraught",
  "ShockingSlayersOil",
  "ThrowingNet",
  "IceRope",
  "ThunderRope",
  "FireRope",
  "LightRope",
  "DarkRope",
  "GuildMembersEmblem",
  "CertificateOfCompetence",
  "MasonsTrowel",
  "EnchantedAlembic",
  "TrackersMap",
  "BerserkersStone",
  "TrappersTag",
  "HitanDoll",
  "RingoldDoll",
  "NuttyDoll",
  "MorkylDoll",
  "FlorzporbDoll",
  "ArachnettaDoll",
  "GuardianKorDoll",
  "SlimeBadge",
  "MagicslimeBadge",
  "SpiderBadge",
  "BatBadge",
  "FairyBadge",
  "FoxBadge",
  "DevilfishBadge",
  "TreantBadge",
  "FlametigerBadge",
  "UnicornBadge",
  "AscendedFromIEH1",
  "WarriorsBadge",
  "WizardsBadge",
  "AngelsBadge",
  "ThiefsBadge",
  "ArchersBadge",
  "TamersBadge",
  "NostroDoll",
  "LadyEmeldaDoll",
  "NariSuneDoll",
  "OctobaddieDoll",
  "BananoonDoll",
  "GlorbliorbusDoll",
  "DistortionSlimeDoll",
] as const;

// export const talismanKind = [];

// export type PotionKind = (typeof potionKind)[number];
export type PotionKind = {
  [K in (typeof potionKind)[number]]?: Talisman;
};

type Talisman = {
  disassembled: number;
  passiveEffectValue: number;
};
